# Generated by Django 4.2.7 on 2024-02-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('tistory', models.CharField(max_length=50)),
            ],
        ),
    ]
