# Generated by Django 5.0.2 on 2024-02-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pageapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passlist",
            name="usernum",
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name="userlist",
            name="usernum",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
